### PR TITLE
Mappers 351, 394, 435. 432 correction.

### PR DESCRIPTION
**Pull request by NRS-NewRisingSun**
Added mappers 351, 394, 435. Correct mistake in mapper 432.

### CODE REVIEW

**Comment by NRS-NewRisingSun** [comment]
> This pull request **introduces 2 alerts** when merging [2f05c22](https://github.com/libretro/libretro-fceumm/commit/2f05c221de52e1018d235edc063d0cffbb045075) into [0b77d74](https://github.com/libretro/libretro-fceumm/commit/0b77d74f87da8ee50033afe9b8a0ebe38f38f31a) - [view on LGTM.com](https://lgtm.com/projects/g/libretro/libretro-fceumm/rev/pr-09339f12cdff2b59ddcf5b94a67645bd1e5cf561)
> 
> **new alerts:**
> 
>     * 2 for Short global name

Resolved by last commit

**Comment by twinaphex** [comment]
@NRS-NewRisingSun  Please start making sure subsequent PRs are C89 compliant. Declare variables at the top of a function or code block. I currently have to manually push commits to fix this.

**Comment by NRS-NewRisingSun** [comment]
I am actively trying to remember it, but without an automated tool to verify compliance with that 33-year-old standard, I cannot guarantee that nothing will slip through in the future.

**Comment by twinaphex** [comment]
@NRS-NewRisingSun  OK, I guess it's not a big deal. I can always take care of these things afterwards.

**Pull request merged**
