### PR TITLE
Rebase based on negativeexponent's repo

### PR DESCRIPTION
**Pull request by LibretroAdmin**
This is a rebase based on negativeExponent's repo. After numerous daily requests asking me to rebase the repo, I've finally decided to go and do it.

However, we need to make sure that the PRs that were merged that did not make it in negativeexponent's repo are still working properly.

So I am inviting stakeholders and previous PR submitters here -
@NRS-NewRisingSun 
@StormedBubbles 
@ClusterM
@tacoschip 
@arpruss
@DigiDwrf 

Apologies if I missed anyone.

Let me know if there is anything missing in this PR that needs backporting.

I will put a deadline on this for next week Friday. If by then I have heard no response, the PR will be merged as is. And if there is something still missing, the person that submitted the PR will have to resubmit it again rebased against the new code.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
BTW, if you click on 'ci/gitlab/git.libretro.com', you can download a core artifact for your platform of choice.

**Comment by LibretroAdmin** [comment]
Fixed sound by adding the core options, however it crashes on content unload instead of cleanly returning to RetroArch.

**Comment by StormedBubbles** [comment]
Hello,

My contribution was pretty minor. I used the existing Libretro implementation of the Power Pad by @arpruss to add the Family Trainer (Japan-only equivalent of the Power Pad for Famicom games) as a selectable device. The current implementation treats each of these devices as a `KEYBOARD` type, while the proposed rebase would switch them to the `JOYPAD` type. The proposed changes look very similar to how lr-mesen handles these devices, and the only danger I can think of is possible interference with hotkey combos. The nature of these devices and how they're mapped in the PR means that the user may be pressing `SELECT` + other buttons simultaneously a lot. The `KEYBOARD` type avoids that issue and allows the user to remap the keyboard keys to joypad buttons anyway via the RetroArch quick menu.

Either way would probably work fine, and I can test it out, but I defer to arpruss as the original contributor of the Power Pad.

**Comment by LibretroAdmin** [comment]
I'll prob give up on this PR, I'm working on a new branch that will backport over most of the relevant changes piece by piece so we avoid any breakage and so we don't lose any PRs either in the process.

**Comment by DusanFamicom** [comment]
I tried it myself, I just didn't know how to put the requests in one download and I still need to write the mappers in Inec.c and Ines.H. Admin please

**Pull request closed without merging**
