### PR TITLE
Revert commits

### PR DESCRIPTION
**Pull request by negativeExponent**
The recent PR were suppose to be parts of more PR to get the entire codebase complete, or at least where i want it to be and in a better working state for easier update and maintenance. Ive come to the point that it would take a lot of time and effort to get all PRs done since each one has to be modified to suit the current codebase, causing a few minor but suppose to be fixable conversion errors. The repo have diverted too much from the time i made the original fork, causing each merges conflicts and needing manual intervention. The recent incident, the reluctance to accept the changes, the consideration of issue without details, the need for third-party confirmation didnt help in giving motivation to do so and complete this. I have worked a long time not just this repo, but on other cores fixing shit nobody else wanted to take and it still amazes me that my intention are getting questioned in favour of..... I would just rather continue working on my fork rather than starting over. Reverting this would be more beneficial for everyone. History is kept(i hoped), for reference.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
I don't understand why you sent this when I told you this in the previous thread -

> I said just now that nothing needs to be reverted and that you can send any followup PRs you had prepared already.

I sent an invite for write permissions too immediately after.

> I would just rather continue working on my fork rather than starting over

You don't have to. I told you this in the previous thread. I made the decision that you could go ahead with this

> The recent PR were suppose to be parts of more PR to get the entire codebase complete, or at least where i want it to be and in a better working state for easier update and maintenance

I said go ahead with this. In fact you can still go ahead with this. That's what I decided on.

I hope you still reconsider.

**Comment by LibretroAdmin** [comment]
Alright then, I'll honor the revert.

It seems other people are also running into segfaults and such so I think it's justified to be worried about the refactors.

https://github.com/libretro/libretro-fceumm/issues/614

**Comment by negativeExponent** [comment]
Like what I've said, issues are suppose to be fixalble. The last one was just probably the index in core options but who knows. Revert is always a prio instead of fixing stuff and move forward

**Comment by negativeExponent** [comment]
your missing the whole point. the issues ARE FIXABLE. dunno how much these CN guys is paying but you are more concerned to appeal to complains without details than the one making the refactoring. the first PR ive already warned of a heads up because due to the NEED of conversion issue will occur and its not a complete set of PRs, but its suppose to be fixable and its not a one-time PR.

should have given me the option of a branch or repo to get the refactoring as stable as THEY want it was. but no. REVERT AND IGNORING ALL THE WORK is the priority, also pleasing them gods.

**Comment by LibretroAdmin** [comment]
Re: CN guys, nobody is paying us anything. I doubt they even have any money to spare. TBH I'm getting fed up with him too.

Re: branch -
Again, I sent you an invite for write rights a month ago. It expired. I sent it to you again a few days ago, I keep telling you that I sent you the invite but it seems you are pretending not to read it. So as far as I'm concerned, you can still accept the invite and create a new branch and work there. All of these options are still available and open.

**Pull request closed without merging**
