### PR TITLE
Multicarts

### PR DESCRIPTION
**Pull request by NRS-NewRisingSun**
Add support for the following mappers: 236, 376, 383
Improve mappers: 3, 57, 134, 178, 196, 219, 242, 314, 319*

* Use hp898f.c only for the old incorrect UNIF bank order to maintain compatibility with the ROM file on Санчес' page, and 319.c for all NES 2.0 ROMs.

### CODE REVIEW

**Comment by LodanZark** [comment]
@NRS-NewRisingSun
Thanks for the great work!
This might be considered an off-topic, but I feel free to ask if you have plans to update the NES2.0 XML database?

**Comment by NRS-NewRisingSun** [comment]
> @NRS-NewRisingSun Thanks for the great work! This might be considered an off-topic, but I feel free to ask if you have plans to update the NES2.0 XML database?

Yes, it will be updated. On the nesdev forums preferably, should they become writable again, otherwise I'll upload it to github.

**Comment by LodanZark** [comment]
@NRS-NewRisingSun 
That's amazing news!
I think using the github to host such database could bring some benefits because it could make it easier to integrate with other projects that are hosted in this platform that use your database, plus it's easier to track down the changes.

**Comment by NRS-NewRisingSun** [comment]
> @NRS-NewRisingSun That's amazing news! I think using the github to host such database could bring some benefits because it could make it easier to integrate with other projects that are hosted in this platform that use your database, plus it's easier to track down the changes.

I do not really like hosting it on github, because I know that somebody will submit a pull request against the XML file, which I cannot use, because the XML file is generated automatically by scanning a directory full of properly-headered .NES files.

**Comment by twinaphex** [comment]
Sorry for the week-long wait.

**Comment by LodanZark** [comment]
@NRS-NewRisingSun Just a quick reminder, https://forums.nesdev.org/ seems to be back to normal ;)

**Pull request merged**
