### PR TITLE
New mapper code

### PR DESCRIPTION
**Pull request by negativeExponent**
lots of changes. see if there is anything worth changing first before we process ig a big merge. Atm, this is the jist of the entire mapper rework, modified to work with this codebase. Regressions might be in place, maybe some incorrect conversions. better alot can test other than just me. The other modifications can be added later bits by bits.

See 1st commit for majority of the change.

BTW, with regards to core options for language translations... is there a way to make it easier to add or remove options without having to do it over and over againt for every language that was added?

@LibretroAdmin @hunterk @hizzlekizzle for review

btw, some unused code left behind, will be cleaned up later when things work or is stable enough.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
oh wow, big PR! This will take a hot minute to review intensively, so is there anything we should be on the look out for in a quicker skim?

**Comment by negativeExponent** [comment]
code-wise, not sure. maybe a heads up especially for those relying on savestates since this will be broken in this PR (and the succeding PRs, probably)

i DO need to know if there is a better way to handle core options for translations. its kinda tedious to add/remove/change options since you have to deal with all languages one by one to update.

maybe, a separate macro/inline/define file for each language used, then a common struct which labels will be replaced depending on language. right now, you have to make/update struct on each.

**Comment by LibretroAdmin** [comment]
> BTW, with regards to core options for language translations... is there a way to make it easier to add or remove options without having to do it over and over againt for every language that was added?

Well, translations are done on the CrowdIn platform, whenever ppl submit new translations there, the repo pulls in new code.

Also I gave you write permissions for this repo too. Not sure if the invite expired, it was sent sometime ago.

**Comment by LibretroAdmin** [comment]
Looks alright to me and first testing seems OK.

I'll be asking dusanfamicom for some more thorough testing. He can file new issue reports based on his findings.

**Comment by hizzlekizzle** [comment]
>crowdin

Yes, this is what I was thinking, as well, but wasn't sure. In that case, you don't need to worry about anything but the english language and then the others are handled by volunteers via crowdin.

**Comment by negativeExponent** [comment]
did it break crowdin fetch thingie though?

**Comment by LibretroAdmin** [comment]
I don't think it should but we'll find out soon enough if/when ppl complain on Crowdin.

**Comment by negativeExponent** [comment]
> > 
> Also I gave you write permissions for this repo too. Not sure if the invite expired, it was sent sometime ago.

it said expired.

**Comment by LibretroAdmin** [comment]
Hi,

I got some feedback from dusan.

> all mappers do not work, the ones for multicart

I asked several times if he could be more specific but that is what he came back with. He says these mappers did work before this PR.

Is it perhaps possible you can leave out the refactors, maybe revert the PR and just pull in the other changes instead that won't cause possible regressions to existing mappers?

**Comment by negativeExponent** [comment]
nothing can be fixed IF no details are provided. if it worked before, then its just a minor fix in the refactor, if its even a code error and not human error. since this was practically "refactored/converted" from my own repo which was already tested (at least for the roms file i have at hand).. the modifications are too many to do this all over again one commit at a time...

you can just revert this repo to what it was and make it a static core, make mine a new repo if you want. but i wont be porting the modifications again one by one. the mapper code alone is dont by a set!

**Comment by LibretroAdmin** [comment]
> nothing can be fixed IF no details are provided. if it worked before, then its just a minor fix in the refactor, if its even a code error and not human error. since this was practically "refactored/converted" from my own repo which was already tested (at least for the roms file i have at hand).. the modifications are too many to do this all over again one commit at a time...
> 
> you can just revert this repo to what it was and make it a static core, make mine a new repo if you want. but i wont be porting the modifications again one by one. the mapper code alone is done by a set and aside from it a big work to do, its incomplete as far as the implementations i was suppose to that needed the refactoring of the entire mapper code to begin with.

I agree that more info should be provided. I'll try my best again.

**Comment by negativeExponent** [comment]
just revert it so people can still use the old core if they want that one. make a separate repo for new fceumm with modifications i can work with or something. i was already woking on new sets to push and this news just make me think its not worth it if the people testing wont even bother giving details. and i dont even trust those CN guys, if theyre the only ones making this isses.

**Comment by LibretroAdmin** [comment]
> just revert it so people can still use the old core if they want that one. make a separate repo for new fceumm with modifications i can work with or something. i was already woking on new sets to push and this news just make me think its not worth it if the people testing wont even bother giving details. and i dont even trust those CN guys, if theyre the only ones making this isses.

Let's not give up motivation yet. I'll keep prodding along to see if I can get some useful information out of him.

Are there any regression tests for mappers so we can determine if changes break something?

**Comment by negativeExponent** [comment]
yeah, more waiting....

**Comment by negativeExponent** [comment]
i have just tested a bunch of multicart based roms, including the newer released ones just a few months ago and everything works, as far as loading the rom itself and selecting a few games.

we should get proper description of the issues instead of making "REVERT THE PR" the defacto when there are issue instead of fixing and moving forward especially when someone is availble to work whichever the kinks are. if its "working before", no reason it will not work, just some kinks to fix due to the conversion from one already about 60% complete repo to here which practially have to compensate for the changes.

if you want this repo to be static, then just revert it back and freeze it for maintenance reason. just be sure whan you want. its always been like this, the waiting causing momentum to break coz we have to listen to reports with missing details.

**Comment by negativeExponent** [comment]
@LibretroAdmin @hunterk @hizzlekizzle

Seriously, you need to revert these changes if im not able to continue to work on this repo. This PR is suppose to be a part of a continues PR i was hoping to be able to do to make it a bit more complete and in sync with my current fork of fceumm. it was not intended to be just 1 PR, even if it works in some places.

Since my PR are getting questioned, not even so much of details then i cant continue working ok it. so much for that "i trust your PR" talk eh.

**Comment by LibretroAdmin** [comment]
I'm caught between two parties here. There is NRS/Dusan on one side and then there is you on the other. I'd prefer we could all work together in the same repo and this emulator just continues to evolve.

I have asked him several times now to list the specific mappers that are broken due to this, I cannot get any specifics out of him except for 'multicarts are all broken now'. It's frustrating but that is what I get reported back.

I do think it is an issue that refactors are made without testing if all the mappers in question still work. So I think it's prob best for now if we revert this and instead, what you could do is focus on just adding more mappers instead of doing core refactors to the code. Or at least if core refactors are done, there should be an easy way to regression test if all the mappers and multicart mappers still work. I think this is a reasonable stance to take since I don't think anyone is helped by mappers suddenly no longer working.

Again none of this is an indictment of your PR and I appreciate all the work you do. I'm also not taking any sides here, I just am choosing the path of least resistance and agreeing that it might be for the best right now to revert this specific PR.

You are able to work on this repo, I'd just suggest adding more mappers instead and just leaving aside the refactors which it seems are prone to breakage.

Please try to understand that in a project with multiple actors/stakeholders involved my position in all this is not an envious one and I'm trying my best to walk on eggshells without trying to offend anyone or make it seem like their input or work is not appreciated. Please try to emphasize with my position here.

**Comment by LibretroAdmin** [comment]
> Since my PR are getting questioned, not even so much of details then i cant continue working ok it. so much for that "i trust your PR" talk eh.

Well I definitely trusted it. Then I got bombarbed by tons of messages from Dusan saying 'everyting is broken now, it's unusable, yadda yadda'. So I've been trying my best to establish what exactly is broken, what happened, which platforms it affects (he also uses PS3 but it's not his only platform) etc. Again it's not for lack of trying, I'm just being told one thing, being told to revert it, then I try to establish what it affects and I just get stuff back like this:

> I have already written to you several times, 99% of mappers do not work, the ones for multicars
hundreds of mappers does not work, logical when 99% of them don't work?

**Comment by LibretroAdmin** [comment]
I think the whole situation for now frankly can be resolved if we just reverted the PR, then you send a new PR with additions that DO NOT like refactor core code in FCEUMM or change files around, just basic functionality added or new mappers. Then we can avoid all the FUD about breakage in mappers and whatnot.

**Comment by LibretroAdmin** [comment]
Alright @negativeExponent , sorry about all that. I talked to NRS and basically I've come to the conclusion that you can continue with the followup PRs. We will see where this goes. Sorry for the whole detour.

**Comment by negativeExponent** [comment]
so your not taking sides and yet the solution is to revert instead of really taking the proper course, and that is to get the info of the problems to resolve. again, if its working before, there is no reason it wont work anymore. since these are the CN guys, i think its more of the "custom hacked" mappers that are specifically modified for specific hacks. i only add roms/mappers i can test with. if someone wants something not there, its can easiliy be added. but i heard enough. this was a waste of time to be honest. again so much for "i trust your PR"

might want to take my rights as well on PX68K as well.

**Comment by LibretroAdmin** [comment]
What are you talking about?

I said just now that nothing needs to be reverted and that you can send any followup PRs you had prepared already.

I was referring to this 

> This PR is suppose to be a part of a continues PR i was hoping to be able to do to make it a bit more complete and in sync with my current fork of fceumm. it was not intended to be just 1 PR, even if it works in some places.

What you concluded is the exact opposite of what I just said. So no, what I'm saying is I side with you. Hell, you can even commit it directly if you feel like the PR is taking too long to merge.

**Comment by LibretroAdmin** [comment]
Sent another invite since the previous one had expired.

**Pull request merged**
