### PR TITLE
Mapper 342 support

### PR DESCRIPTION
**Pull request by ClusterM**
Ported from the fceux. It's a homebrew mapper: https://www.nesdev.org/wiki/NES_2.0_Mapper_342
Seems like development is over.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
Make sure comments are C-style too, not C++.

**Comment by ClusterM** [comment]
Ok. Thank you!

**Comment by LibretroAdmin** [comment]
Took a bit of time but I made the commit here -
https://github.com/libretro/libretro-fceumm/commit/049b341aa17277ca6a216735f76adc2540957758

Is there a way to silence this warning without breaking the code?

> src/boards/coolgirl.c: In function 'COOLGIRL_Sync_CHR':
src/boards/coolgirl.c:389:98: warning: missing terminating ' character
  389 |         wire shift_chr_right = ENABLE_MAPPER_021_022_023_025 && ENABLE_MAPPER_022 && (mapper == 6'b011000) && flags[1];
      |                                                                                                  ^cc -c -osrc/boards/emu2413.o src/boards/emu2413.c -DGIT_VERSION=\"" 049b341"\" -O2 -DNDEBUG -std=c89  -Wno-write-strings -D__LIBRETRO__ -DPATH_MAX=1024 -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565 -DHAVE_NTSC_FILTER -Isrc/ntsc    -Isrc/drivers/libretro -Isrc/drivers/libretro/libretro-common/include -Isrc -Isrc/input -Isrc/boards

**Comment by ClusterM** [comment]
`wire shift_chr_right = ENABLE_MAPPER_021_022_023_025 && ENABLE_MAPPER_022 && (mapper == 6'b011000) && flags[1];`

It's just a comment with related FPGA code, you can remove it.

**Comment by LibretroAdmin** [comment]
There are so many gremlins in this code.

'0b011000'

This completely breaks the MSVC builds -

> src/boards/coolgirl.c(393) : error C2059: syntax error : 'bad suffix on number'
> src/boards/coolgirl.c(393) : error C2146: syntax error : missing ')' before identifier 'b011000'

**Comment by ClusterM** [comment]
Ok, i'll do it tomorrow.

**Comment by LibretroAdmin** [comment]
Thanks.

**Pull request merged**
