### PR TITLE
user-adjustable Zapper tolerance

### PR DESCRIPTION
**Pull request by arpruss**
The original Zapper was a pretty fuzzy analog device with a field of view that was far from pinpoint accuracy. As a result, somewhat off-target hits would presumably get registered, and this was a part of the expected difficulty of the games. The current fceumm Zapper code adds four pixels around target areas to compensate. That may not be enough: some games are likely still harder than they should be. 

This PR makes the target tolerance user-adjustable. It also makes the added target area rounded, which is closer to the round nature of the fuzziness of the original Zapper.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi @negativeExponent  and @hizzlekizzle , try to see if you guys can review this. Thanks.

**Comment by hizzlekizzle** [comment]
In talking with negativeExponent, I believe his main concern is that the range is really huge. That is, 32px tolerance is larger than the white square in the zapper test ROM he posted in the issue thread:
image

**Comment by arpruss** [comment]
But is there any harm in giving the user more freedom to make games easier?

I would be OK with reducing the range to 20 or 24 if people prefer.

**Comment by arpruss** [comment]
I reduced the range to 20. Is that better?

**Comment by negativeExponent** [comment]
whats the point of having to "aim" at all when you have this much offset when a target hitbox is 1 tile big (ducks having 4x4 tiles).

**Comment by arpruss** [comment]
The code already allows various things that make games easier. Not only does it allow cheats in general, but it lets people have cross-hairs or use a touch screen. Playing with cross-hairs and a small offset can be easier than playing with a larger offset and no cross-hairs. I haven't tried touchscreen, but I expect it's pretty easy, too. So I see no harm allowing a range of 20. My general approach to programming is to give users as much as freedom as possible.

**Comment by negativeExponent** [comment]
thats irrelavant to the issue at hand. this literally breaks accuracy just for the convenience. crosshairs can be disabled. cheat have gamegenie which are legit hardwares (or should i say something that exists). please let me know a gun hardware with adjustable tolerance and or an emulator which even has this adjustable.

**Comment by arpruss** [comment]
You can also disable this, just like you can disable crosshairs.
And the way I understand the original analog hardware, if you turn up the TV brightness (and maybe move away from the screen) you might get a similar effect.

**Comment by negativeExponent** [comment]
once seen, it cannot be unseen.. hence i disagreed on making this configurable, and to be this much when a target can be as small as 1 tile.

**Pull request merged**
