### PR TITLE
Add mapper 342 (Coolgirl boards)

### PR DESCRIPTION
**Pull request by SumavisionQ5**

### CODE REVIEW

**Comment by SumavisionQ5** [comment]
This mapper is still in development, and the codes I submitted is outdated, which makes some of games in multicatridges not working. So I will close it. Sorry for it.

**Comment by Nesmen89** [comment]
Please Add

**Comment by negativeExponent** [comment]
don't know how incomplete this mapper code is, but the cart requires 256K of chrram, which is missing in both ines.c and unif.c implementaions. Apply it, and some of the games should work

**Comment by SumavisionQ5** [comment]
> Please Add
> try it.
> on other emulators also work
> it also works on fceux

If you want to try it, you can get codes from my fork. But since it's not complete, I will leave it to someone else who can finish it to add support for this mapper. This mapper is still diligently updated by ClusterM and more mappers are supported. For more infomation, please visit: https://github.com/coolgirl-multicart/coolgirl-famicom-multicart

**Comment by NikolkaMedova** [comment]
> don't know how incomplete this mapper code is, but the cart requires 256K of chrram, which is missing in both ines.c and unif.c initializations. Apply it, and some of the games should work


Hi, could you add? When do you understand that? I have some multicart coolgirl to test

**Pull request closed without merging**
