### PR TITLE
Mappers

### PR DESCRIPTION
**Pull request by retro-wertz**

### CODE REVIEW

**Comment by retro-wertz** [comment]
cleaning up PR

**Comment by MILANEK11** [comment]
Please Add Mappers INes 2.0 
I have mapper codes, I'd send them to you
Thank you very much , you are very nice

**Comment by MILANEK11** [comment]
bmc-830013-b 
90-in-1 Hwang Shinwei (Unl)[U][!] 
:-)  I read that you add it
:-)  Thank you very much :-*

**Comment by MILANEK11** [comment]
Hello, thank you for your work :-)
please add JY Company Mappers? (267,281,282,295,351,356,358,361,362,363,364
and 256 mapper VRT and Board MINDKIDS 143 in 1
Thank you very much

**Comment by MILANEK11** [comment]
Please write me :-(

**Pull request closed without merging**
