### PR TITLE
c89 fix

### PR DESCRIPTION
**Pull request by joolswills**
now builds on visual studio 2003 :)

### CODE REVIEW

**Comment by Alcaro** [comment]
Now those static bools discard their state every time. Move the initializers back to the declarations. (Or remove them entirely, all platforms I've seen initialize statics and globals to zero if not otherwise specified.)

**Comment by joolswills** [comment]
woops. sorry.

**Comment by joolswills** [comment]
does that look better ?

**Comment by Alcaro** [comment]
That one looks fine. You're swapping FCEU_FDSSelect and RETRO_DEVICE_ID_JOYPAD_R, but there's no way that would screw anything up. Thanks.

**Pull request merged**
